version: "3.9"
services:
  postgres:
    image: "postgres:14.2"
    container_name: "tam-develop-pg"
    hostname: postgres-service
    network_mode: bridge
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=application-db
    ports:
      - "15432:5432"
