spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/application-db
    username: dbuser
    password: supersecret
  jooq:
    sql-dialect: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    open-in-view: false
    show-sql: true
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: file:./web/src/main/resources/templates/
  flyway:
    locations: classpath:/db/migration,classpath:/db/testdata
